### ISSUE TITLE
new version - incompatibilities (309)

### ISSUE THREAD

**Issue by oblomov-dev** [abap2UI5/abap2UI5#311] opened 2023-06-26 17:33 UTC
Could not avoid some incompatibilities with https://github.com/abap2UI5/abap2UI5/pull/309

Changes:
* no global or static attributes anymore, framework <-> app communication only via the client interface from now on
    * need to update the GET and POST calls of the handler class
* reorganized the client->set_next method
    * set_next is deleted, use view_display, popup_display, set_scroll_pos etc. instead
* binding:
    * before: _bind -> two way (changes are transferred to the backend)
    * now: _bind -> one way (changes are NOT transferred to the backend anymore)
     * use _bind_edit for two way binding now
* new app and view control flow
    * views are displayed once and then shown until a new view is sent to the frontend, no rerendering after each request anymore, only the model is updated (and with this the view), check out the demo repository to have some examples
* popups and popovers are separated now

Some refactoring is needed, if you find bugs open an issue. You can still use the older "compatible" version, created before:
https://github.com/abap2UI5/abap2UI5/releases/tag/v.1.10.4

**Comment by axelmohnen** [comment] 2023-06-27 06:55
Hi,
The HTTP handler class doesn't work any more. 
Do you have a implementation example for me?
Thanks,
Axel

**Comment by oblomov-dev** [comment] 2023-06-27 07:34
yes updated the readme or use this:
```abap
METHOD if_http_extension~handle_request.

   DATA lt_header TYPE tihttpnvp.
   server->request->get_header_fields( CHANGING fields = lt_header ).

   DATA(lv_resp) = SWITCH #( server->request->get_method( )
      WHEN 'GET'  THEN z2ui5_cl_http_handler=>http_get( )
      WHEN 'POST' THEN z2ui5_cl_http_handler=>http_post(
         body      = server->request->get_cdata( ) 
         path_info = lt_header[ name = `~path_info` ]-value ) ).

   server->response->set_header_field( name = `cache-control` value = `no-cache` ).
   server->response->set_cdata( lv_resp ).
   server->response->set_status( code = 200 reason = `success` ).

ENDMETHOD.
```

**Comment by axelmohnen** [comment] 2023-06-27 11:46
Thanks a lot. Issue has been solved.

**Comment by oblomov-dev** [comment] 2023-07-01 19:00
@nomssi @Th0masMa @axelmohnen 
Needed to change some public APIs again, so be aware before the next pull!

Check out the following tweet to see for example why this is all needed:
https://twitter.com/abap2UI5/status/1675074394710765568
Or this demos:
<img width="420" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/b46b299f-5a10-417e-bf34-46572eb386bb">

And the other good news:
**The refactoring of abap2UI5 is finished for now!** ;)

Following adjustments needed:
(1) the call of the get method, name of variables changed from "name" to "n" and from "value" to "v":
<img width="852" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/d83d9e73-1654-4fad-bd5e-6d80376feacd">
(2) interface of the cursor method changed:
<img width="362" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/ed3ed223-4aad-4ca9-92f4-222d4c94cccf">
(3) Attributes of the xml view class are protected now:
<img width="313" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/354dd315-61b3-4213-9ee4-acc635764666">
(4) _event method importing parameter "check_view_transit" changed to "check_view_destroy":
<img width="513" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/b0e7e1a4-30dd-4764-b61b-85a9f7f32462">

Best regards.

**Comment by Th0masMa** [comment] 2023-07-01 19:56
Hi
Great work. I test it tomorrow.

Best Regards
Thomas

oblomov ***@***.***> schrieb am Sa., 1. Juli 2023, 21:00:

**Comment by axelmohnen** [comment] 2023-07-03 07:55
Hi,
it works! In my case I only had to adapt the HTTP handler implementation.
Thanks,
Axel

**Comment by oblomov-dev** [comment] 2023-07-07 04:50
@axelmohnen cleaned up the nested interface and made a consistent naming of popups/popupovers/nested view. don't forget to refactor after the next pull:
<img width="341" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/896c947d-6dc3-4ea3-832b-b343eadbaef3">

**Comment by oblomov-dev** [comment] 2023-07-09 08:22
@axelmohnen @nomssi @WegnerDan @Th0masMa updated with some incompatibilities. use the last tag to avoid refactoring:
https://github.com/abap2UI5/abap2UI5/releases/tag/v1.20.2

The HTTP Call is now cleaned up and smaller:
<img width="500" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/bf752910-e94d-48fe-baa5-29432085e89f">

The start URL of app changed, so update your favorites:
Before: url/path/appname
Now: url/path?app_start=appname

The IDs of the apps in the get method are now nested in s_draft:
<img width="500" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/24374da1-13a0-4e48-b89a-2d652c126bf6">

Let me know if there are any issues.

**Comment by axelmohnen** [comment] 2023-07-10 05:36
Hi,
the new HTTP Call and the app start parameter are working fine.
I saw that the method POPUP_CLOSE has been replaced by POPUP_DESTROY in the client interface.
Unfortunately, since than I can open an popup, but can't close anymore. I only see the endless "busy indicator".
For test reason I changed the "src" parameter in the config to the OPENUI5 and it worked.
We are using locally SAPUI5 version 1.71.48. The popup open and closing was working before with that version.

Thanks,
Kind regards
Axel

**Comment by oblomov-dev** [comment] 2023-07-10 08:17
Hi,

updated the repo, there was one incompatibility with older version, but it should work now (https://github.com/abap2UI5/abap2UI5/pull/367).

updated the snippet:
https://github.com/abap2UI5/ext-integration_fiori_launchpad/blob/main/webapp/controller/View1.controller.js

And also adjusted the main repo https://github.com/abap2UI5/abap2UI5/pull/368

You can try again.

**Comment by axelmohnen** [comment] 2023-07-10 09:29
Hi,
I can confirm, "Popup destroy" works again for version 1.71.
Thanks a lot.
Kind regards
Axel

**Closed** 2023-09-11 13:22 UTC
