### ISSUE TITLE
FLP Connector - 400 Session Timed Out 

### ISSUE THREAD

**Issue by christianguenter2** [abap2UI5/abap2UI5#1453] opened 2024-09-25 08:26 UTC
Steps to reproduce:
1) Integrate Samples App or any sticky demo app into FLP and open sticky sample
![image](https://github.com/user-attachments/assets/49ebdd56-7bcf-48d3-bb53-e837e15c6271)
![image](https://github.com/user-attachments/assets/115fb0c4-c64f-4cba-a86f-35e5df640523)
2) Do something in sticky sample app, e.g. increase counter (1) and navigate back with the FLP back navigation (2)
![image](https://github.com/user-attachments/assets/6aeba170-e5f2-4a59-afeb-28b02976a543)
3) Open app again via tile 
![image](https://github.com/user-attachments/assets/1c4b9f46-ae2c-4ab8-bc49-81fb2d9bb041)

Note, the error does  **not** occur when navigation back with the samples app back navigation and then back with FLP navigation to the FLP start page
![image](https://github.com/user-attachments/assets/d9c30e47-10cf-41bc-90c1-e53cef4d6a40)

**Comment by oblomov-dev** [comment] 2024-09-25 09:34
thanks for testing and the documentation.

when you press the "manual" back, the session is manually closed:
https://github.com/abap2UI5/abap2UI5-samples/blob/main/src/z2ui5_cl_demo_app_137.clas.abap#L76

this is not triggered when you press back on the launchpad, i guess this is the root cause.
can you check if you run into the same problem with the "manual" back by commenting out the line?

**Comment by christianguenter2** [comment] 2024-09-25 10:29
> can you check if you run into the same problem with the "manual" back by commenting out the line?

Yes, If I comment out this line, the same error occurs for "manual" back


> this is not triggered when you press back on the launchpad, i guess this is the root cause.

Hm, I thought that what's the HEAD request is for? Which is triggered while FLP back navigation
![image](https://github.com/user-attachments/assets/d58eaf2e-ed65-4c0c-91df-43f92735c9be)

**Comment by oblomov-dev** [comment] 2024-09-25 10:36
yes i copied 1:1 the new logic to the connector so you find the lines here now L718-L738:
https://github.com/abap2UI5-connectors/fiori-launchpad-connector-onpremise/blob/main/src/02/zabap2ui5.wapa.component.js#L718-L738

you can check with a breakpoint if the code gets triggered. maybe we need some more magic there?

**Comment by christianguenter2** [comment] 2024-09-25 10:39
Yes, HEAD request is sent and handler is triggered.

**Comment by oblomov-dev** [comment] 2024-09-25 10:44
does the frontend wait for the backend?

**Comment by christianguenter2** [comment] 2024-09-25 11:37
No, it does not.

**Comment by oblomov-dev** [comment] 2024-09-25 11:50
replace the exit function with this (added an await that the frontend waits for the backend, but just guessing):
```
exit: async function() { // Marking the function as async
    if (sap.z2ui5.contextId) {
        try {
            await fetch(sap.z2ui5.pathname, {  // Adding await to fetch
                method: 'HEAD',
                keepalive: true,
                headers: {
                    'sap-terminate': 'session',
                    'sap-contextid': sap.z2ui5.contextId,
                    'sap-contextid-accept': 'header'
                }
            });
            console.log('Session terminated successfully');
        } catch (error) {
            console.error('Failed to terminate session:', error);
        }
    }
    if (UIComponent.prototype.exit) {
        UIComponent.prototype.exit.apply(this, arguments);
    }
},
```
maybe we are lucky, otherwise i can set up the launchpad in a few days and check this again.

**Comment by christianguenter2** [comment] 2024-09-25 12:26
No luck. Session was terminated successfully
![image](https://github.com/user-attachments/assets/62493331-aa96-4046-a049-8a6f50fb5256)
but still the same `400 Session Timeout` error.

**Comment by oblomov-dev** [comment] 2024-09-25 13:11
ah too bad, maybe we should call in the HEAD implementation the same as we do when calling  set_session_stateful( client = client stateful = abap_false ). theoretically it should be the same. but before i start changing something without having a deeper understanding we can better wait, maybe @mzinnoecker has a hint for us.

**Comment by mzinnoecker** [comment] 2024-09-25 14:52
@oblomov-dev would you like to merge #1455 and @christianguenter2 to test again afterwards?
From my opinion that should work

**Comment by oblomov-dev** [comment] 2024-09-25 15:08
thank you, merged. and copied to the launchpad connector (hopefully without typo) with https://github.com/abap2UI5-connectors/fiori-launchpad-connector-onpremise/commit/7f9960471c6598088d2da257ea0d2e804ea90e00

@christianguenter2 you can just pull from main again and test it.

**Comment by christianguenter2** [comment] 2024-09-25 16:31
It works 🚀 Thank you guys for your great support. Very much appreciated ❤️

**Closed** 2024-09-25 16:31 UTC

**Comment by oblomov-dev** [comment] 2024-09-25 16:42
nice! thanks to both of you for testing and fixing!

i guess with the new frontend structure it would now also be possible to get rid of the global sap variable and make everything more local. will refactor it one day but for the moment its nice to see that it works as it is now...

just curious:
does someone of you know if statefulness also works through sap cloud connector? 
setup for example: 
on_premise sap -> cloud_connector -> [ui5 app on btp](https://github.com/abap2UI5-connectors/btp-connector)

otherwise i will give it a try and find it out :)

**Comment by mzinnoecker** [comment] 2024-09-25 16:47
nice!

> does someone of you know if statefulness also works through sap cloud connector?

yes, as long as the sap-contextid header is passed through (which is, seen that already in a fiori app on s/4 2023), no problem :)

**Comment by oblomov-dev** [comment] 2024-09-25 16:52
cool! 😎
