### ISSUE TITLE
Error loading view: unexpected token '&'

### ISSUE THREAD

**Issue by mail4deep2000** [abap2UI5/abap2UI5#1263] opened 2024-07-10 15:59 UTC
Hello Team,

Clicking the tile for the abap2ui5 app on the fiori launchpad results in the error below.

![image](https://github.com/abap2UI5/abap2UI5/assets/38676407/3307b65c-f5b1-427d-91b7-686bfa7fded3)

Steps performed:
1) ABAP2UI5 is installed in the latest version
2) ABAP2UI5 Launchpad Connector is installed
3) Launchpad customizing is performed as detailed in this link - [[nstallation & Configuration](https://www.linkedin.com/pulse/copy-abap2ui5-host-your-apps-sap-fiori-launchpad-abap2ui5-ocn2e/)](https://www.linkedin.com/pulse/copy-abap2ui5-host-your-apps-sap-fiori-launchpad-abap2ui5-ocn2e/)

this abap2ui5 app works fine when we launch it directly in the browser( which is not in the Fiori Launchpad )

Any known resolutions around this issue please?

**Comment by oblomov-dev** [comment] 2024-07-11 08:40
Hi @mail4deep2000,

so far couldn't reproduce the error.

This means you can call abap2UI5 directly via http without problems:
/sap/bc/z2ui5

And also the Launchpad Connector App without problems:
/sap/bc/ui5_ui5/sap/zabap2ui5/index.html

<img width="200" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/c6ea3b08-5537-400b-a856-84281052ec57">

But only if it becomes a tile in the launchpad you get the error?

**Comment by cwildt** [comment] 2024-07-11 10:26
Same here (NW 7.4)

**Comment by oblomov-dev** [comment] 2024-07-11 11:23
can you call the http endpoint and connector app directly without problems?

**Comment by cwildt** [comment] 2024-07-11 16:14
Both are working fine.
Installed SAPUI5 Version is 1.71.67

**Comment by oblomov-dev** [comment] 2024-07-11 16:43
Hi together,

checked the issue again and bootstrapped with different versions. i could reproduce the error on UI5 versions 1.7x and 1.8x. So unfortunately the launchpad connector is only compatible from:
1.96 (2111) | 7.56 | SAP FIORI FES 2021 FOR S/4HANA (SAP Note 3050199)

Possible workaround: Let the launchpad bootstrap with a newer UI5 version via CDN, but never tried something into this direction. I will update the readme.

**Comment by mail4deep2000** [comment] 2024-07-11 20:35
> Hi @mail4deep2000,
> 
> so far couldn't reproduce the error.
> 
> This means you can call abap2UI5 directly via http without problems: /sap/bc/z2ui5
> 
> And also the Launchpad Connector App without problems: /sap/bc/ui5_ui5/sap/zabap2ui5/index.html
> 
> <img alt="image" width="200" src="https://private-user-images.githubusercontent.com/102328295/347745491-c6ea3b08-5537-400b-a856-84281052ec57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3Mjk1ODEsIm5iZiI6MTcyMDcyOTI4MSwicGF0aCI6Ii8xMDIzMjgyOTUvMzQ3NzQ1NDkxLWM2ZWEzYjA4LTU1MzctNDAwYi1hODU2LTg0MjgxMDUyZWM1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMVQyMDIxMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMTA5ZTg1YTQxYzk4ZmRiNTc0MmFhNjg5NjNiMTk1YjdhOTIyOTg5MDRmNzRkNGYzN2Y2YjJjYWEyM2NjNDFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.euqM9ne0QC6gyYtKCCspYBYEg3In4b4U38beMOHY1nk">
> But only if it becomes a tile in the launchpad you get the error?

Hi @oblomov-dev ,

When i launch /sap/bc/ui5_ui5/sap/zabap2ui5/index.html, ( i understand abap2ui5 app?), works fine for me.

![image](https://github.com/abap2UI5/abap2UI5/assets/38676407/091f9120-7d6f-4d84-8be4-4c747f6b89ab)

when i try /sap/bc/z2ui5 - Launchpad app, it does not work( get a blank screen with error shown below in developer tools):
![image](https://github.com/abap2UI5/abap2UI5/assets/38676407/df1e53a6-eb1d-4479-ba86-6d7f952566cc)


The ui5 verion we have on the system is 1.71

Please let us know if you need more inputs.

**Comment by oblomov-dev** [comment] 2024-07-12 07:09
hi @mail4deep2000,

checked this yesterday, the minimum requirements for the launchpad connector is:
SAP Netweaver (v.7.56) or S/4 2021 (Standard ABAP)

You need minimum UI5 version 1.9x, so unfortunately you are too low.

**Comment by oblomov-dev** [comment] 2024-07-23 07:45
i close this one, just reopen if you have further questions

**Closed by oblomov-dev** 2024-07-23 07:45 UTC
