### ISSUE TITLE
Launchpad error with app UI5

### ISSUE THREAD

**Issue by rafeodev** [abap2UI5/abap2UI5#1557] opened 2024-11-21 15:19 UTC
Hello,

If the Tile is created with application type = URL then abap2ui5 works. However if the application type is SAP Fiori App then the tile cannot be loaded. Error "failed to load component for navigation intent XXX (=target mapping).

Regards,

Mehdi

**Comment by rafeodev** [comment] 2024-11-21 17:17
Hello,

See attached file regarding the tile error. 

![image](https://github.com/user-attachments/assets/0db1b2e6-238d-40bf-ac5a-78f3a74b794b)

Target mapping.

![image](https://github.com/user-attachments/assets/3b9c63b9-cdff-482f-9c97-831593254f4d)

Tile
![image](https://github.com/user-attachments/assets/a3034028-77c7-4628-a3d6-f7f517cebaeb)

Let me know if you need more.

Mehdi

**Comment by rafeodev** [comment] 2024-11-21 19:20
Yes à mistake with the copy and paste. Do you need a screenshot of the tile too ? Or anything else ?

**Comment by christianguenter2** [comment] 2024-11-21 20:13
> Yes à mistake with the copy and paste. Do you need a screenshot of the tile too ? Or anything else ?

yes. The more information the better. Also check browser dev tools. Especially the console and the network tab.

**Comment by rafeodev** [comment] 2024-11-22 09:11
Hello,

Here are the screenshots.

![image](https://github.com/user-attachments/assets/86da7584-7cc9-440c-a992-80e8ed31f0d5)

![image](https://github.com/user-attachments/assets/3e6af3f5-f153-43e3-a794-bd645af2bf7d)

![image](https://github.com/user-attachments/assets/fa74ef94-3da5-45c5-92cb-5cdbe28ebb48)

![image](https://github.com/user-attachments/assets/cd06117e-d0e2-4700-9323-70957a192977)

Also check the installation. Everything looks ok.

![image](https://github.com/user-attachments/assets/e0a6d09a-243a-4632-a1bc-8ae0949023f0)

KR,

Mehdi

**Comment by christianguenter2** [comment] 2024-11-22 11:44
> Network tab.
> 
> ![image](https://private-user-images.githubusercontent.com/85461870/388918124-77a4e49d-bd33-4db9-99bd-68ff1d51cdbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNzU2ODcsIm5iZiI6MTczMjI3NTM4NywicGF0aCI6Ii84NTQ2MTg3MC8zODg5MTgxMjQtNzdhNGU0OWQtYmQzMy00ZGI5LTk5YmQtNjhmZjFkNTFjZGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDExMzYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzNDBmYmQ0MGVmM2ExNWJjYWUyNTI2NDQ4NGE1YzdhYjNjZjUwNzUxZGFlODJjNGFmNDRlYWQ0Y2Y1NGE3NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NgcNR40mYTrtKDP4VzZlENC7ZqKqRt-2MNsQzosnbMU)
> 
> ![image](https://private-user-images.githubusercontent.com/85461870/388918229-b1abb99d-664c-493a-8e1d-b2d60998417b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNzU2ODcsIm5iZiI6MTczMjI3NTM4NywicGF0aCI6Ii84NTQ2MTg3MC8zODg5MTgyMjktYjFhYmI5OWQtNjY0Yy00OTNhLThlMWQtYjJkNjA5OTg0MTdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDExMzYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5OGUyYWQ1NTQ1OGRmNGQ0MjgzOGQ0ZjFiYTYyNmEyOTAyYmMyNjYwMTFiYjc2ZTIwZGUyOWNiYzFkZGU0YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.D-u7iEYuJxxiJ4LowNKBNg_Nxi0YVBalu7GeiHTLvUs)
> 
> ![image](https://private-user-images.githubusercontent.com/85461870/388918315-afb51bb0-3893-4a0a-990c-25e3092ef8db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNzU2ODcsIm5iZiI6MTczMjI3NTM4NywicGF0aCI6Ii84NTQ2MTg3MC8zODg5MTgzMTUtYWZiNTFiYjAtMzg5My00YTBhLTk5MGMtMjVlMzA5MmVmOGRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDExMzYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzYjNlNmFiMTUxZjllMTg3OWFkY2MyOGZkNTkwNmUzZDYxZWQzZTYyM2VhMzBmMTJjOTE3NTc4ZGFkMTVhOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MfhS_hM7e3yhWvZu7bOrttoZHfa9tIcnJWvI1w-HqsE) ![image](https://private-user-images.githubusercontent.com/85461870/388918403-06da41a9-43c2-4c6a-abeb-a083b498983e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNzU2ODcsIm5iZiI6MTczMjI3NTM4NywicGF0aCI6Ii84NTQ2MTg3MC8zODg5MTg0MDMtMDZkYTQxYTktNDNjMi00YzZhLWFiZWItYTA4M2I0OTg5ODNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDExMzYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkYmIxZGY0ODcwYTQ0NmY0MDRjODQ0NmIyMTFlYjMwNDZiMTUyNWE0NDczYjZiYWUwYWVhZDc3YjE2ZWVhZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2Zux8L5fmmwBthMd3W_oinQOKz05GKtKd4_h4mNoO38)

`Component-preload.js` always fails, so that doesn't matter. Are there further failed requests?
You can try to recalculate the app index with report `/UI5/APP_INDEX_CALCULATE`.

**Comment by rafeodev** [comment] 2024-11-22 12:42
Program run but still get the same error.

models.js also failed.

![image](https://github.com/user-attachments/assets/393a9545-bc76-4c52-b058-1871bd73028d)

**Comment by christianguenter2** [comment] 2024-11-22 13:34
Hm, I'm out of ideas. Maybe @oblomov-dev or others have hints?

**Comment by oblomov-dev** [comment] 2024-11-22 19:38
mhh....

can you check if you can call the ui5 frontend without launchpad first? I mean call the index.html directly with:
<<your system url>>/sap/bc/ui5_ui5/sap/z2ui5/index.html

then we know if the frontend app causes the problem or if its something in the launchpad configuration.

**Comment by francisco-milan** [comment] 2024-11-22 19:38
Hi guys,

It seems like I’m experiencing the same issue as @rafeodev . Interestingly, this used to work fine before, so I’m not sure what changed. Just wanted to let you know that it’s happening on my end too.

Let me know if you find any updates or solutions!

![image](https://github.com/user-attachments/assets/a3f18fa1-531f-4dc4-be67-e9b35aecdb57)

**Comment by oblomov-dev** [comment] 2024-11-22 19:39
mhh....

can you check if you can call the ui5 frontend without launchpad first? I mean call the index.html directly with:
your_system_url/sap/bc/ui5_ui5/sap/z2ui5/index.html

then we know if the frontend app causes the problem or if its something in the launchpad configuration.

**Comment by francisco-milan** [comment] 2024-11-22 19:52
In my system I tried with http://vhcala4hci:50000/zabap2ui5/index.html

![image](https://github.com/user-attachments/assets/3d61633a-8b83-4c35-ab78-ef2f4bcde40f)

And here's the result:

![image](https://github.com/user-attachments/assets/73152e3d-2bf2-46a8-aa79-71402d9fc23d)

**Comment by oblomov-dev** [comment] 2024-11-23 11:22
mhh... if you can start the normal bsp page, it should behave as any other UI5 app so i am wondering that it does not work with the launchpad. are there any other ui5 apps in your system? the should produce the same issue i guess...

checked the commit history, but nothing important changed since a month, can you maybe install the last tag and check if you still have this problem?
https://github.com/abap2UI5/frontend/releases/tag/1.135.0-classic

**Comment by rafeodev** [comment] 2024-11-23 15:02
Indeed, same issue happens with any abap2ui5 app demo.

**Comment by rafeodev** [comment] 2024-11-24 00:30
if needed, we can make a short vision conf so that I can share my screen. Feel free.

**Comment by francisco-milan** [comment] 2024-11-24 01:53
I’m attaching two recordings to this post:

The first recording is from September 3rd, 2024, when I tested the Fiori Launchpad and everything was working as expected at that time. Unfortunately, I haven’t used the Launchpad since then, so I don’t have a more recent recording.

The second recording shows the same steps as the first, but this time, we encounter the error message.

I hope these videos help clarify the issue.

https://github.com/user-attachments/assets/8ad481c8-a1d5-4814-a37c-1939eca7da1b


https://github.com/user-attachments/assets/a86cf604-8c8c-4350-8ada-6793414706a7

**Comment by oblomov-dev** [comment] 2024-11-24 09:11
To be honest, I’m not an expert in Launchpads — for instance, it doesn’t work on my developer edition either, so it seems to be buggy at times. I can only provide an abap2UI5 app like any other freestyle UI5 app, but the rest are more Launchpad-related issues that I can’t necessarily address. But we can definitely give it a try:

@rafeodev  are there any other UI5 apps running on your Launchpad? Specifically, non-abap2UI5 apps like standard UI5 freestyle or Fiori Elements apps? This would help us determine if it’s a general FLP issue or something specific to the abap2UI5 frontend

@francisco-milan could you try installing an older version of the frontend on your system? For example, you could use a tag from last September or October. This would allow us to compare and check if any breaking changes might be causing the issue

**Comment by francisco-milan** [comment] 2024-11-24 19:18
Hi @oblomov-dev,

Thanks for the suggestion! I’ll try installing an older version as you mentioned. I’ll let you know the results once I’ve tested it.

**Comment by francisco-milan** [comment] 2024-11-25 01:28
Hi @oblomov-dev ,

I’ve tried installing the versions with tags from September and October, but the result was the same. My guess is that with those versions, we may need to use a specific version of the Handler Class, as I know the Handler Class has been evolving over time. This might be causing the issue.

Let me know if you'd like me to try anything else or if you need further details from my side.

**Comment by oblomov-dev** [comment] 2024-11-25 19:48
mhh the sap/gantt error should be not a problem, i fixed it anyway because it was not nice having it in the console with https://github.com/abap2UI5/abap2UI5/pull/1576

The main change of yesterday was that the frontend now bootstraps with the on-stack ui5 library:
https://github.com/abap2UI5/abap2UI5/blob/main/app/webapp/index.html#L15

so it should behave now exaclty as any other ui5 app in the system and also work in the launchpad. @christianguenter2 can you check again of calling the frontend standalone does work on your side?
<system>/sap/bc/ui5_ui5/sap/z2ui5/index.html

on my system its all good (ABAP Dev 2022).

if this still does not work in the launchpad, can you switch back to the latest tag and check again? we need to find a working version that we can make a diff and find out which line causes the problem.

i am a bit lost because there were no major chances since a month, and i also don't use the on-premise launchpad so it its some effort for me to always set this up on my machine. hope we can find it this way.

@francisco-milan don't know why the old tags don't work, you just need to adjust the http handler to the former version than it should work as it did before.

**Comment by christianguenter2** [comment] 2024-11-25 20:09
Yes, frontend standalone works. Interestingly some abap2UI5 apps running in the FLP are working. All configured the same.
Switching the frontend repo to tag 1.135 solved the problem for me. But, then I switched back again to latest `standard` branch and now I cannot reproduce the error anymore. Everything is working again as excpected.

I'll try again tomorrow.

**Comment by oblomov-dev** [comment] 2024-11-25 20:38
thanks a lot for testing! 
mhh yes maybe one of the too many caches is not initialized, but there is always some magic with the launchpads. there are also no big changes between 1.135 and latest... but yes just give it try again and let us know if you can reproduce any errors.

**Comment by christianguenter2** [comment] 2024-11-26 06:15
yeah, dark magic of FLP...
Anyway, I was able to reproduce the error few more times by switching tags and branches. Not consistently by hey at least I was able to solve it always by the following steps.

1) Recalculate app index of `z2ui5` with report /UI5/APP_INDEX_CALCULATE
![image](https://github.com/user-attachments/assets/f18e791e-1e07-4381-a8a8-deb5af3ec02c)
![image](https://github.com/user-attachments/assets/093d087f-4d7d-48b3-b7c4-75c16046af5b)

2) Recalculate index of distribution layer with report /UI5/APP_INDEX_CALCULATE (if tab isn't visible try switching to another tab, then it usually appears)
![image](https://github.com/user-attachments/assets/2a480005-f9f9-46e8-a432-456494957665)
![image](https://github.com/user-attachments/assets/389f2be1-d75b-4dbb-aa81-e5b5e4202440)

3) Invalidate http caches in transaction SMICM
![image](https://github.com/user-attachments/assets/f6568b5e-0588-4a98-83cc-f1bd58e0dd64)

4) Clear browser caches and hard reload

@francisco-milan and @rafeodev can you try if that works for you, too?

**Comment by francisco-milan** [comment] 2024-11-26 06:41
Hey @christianguenter2,

Thanks for sharing this info! I’ll give it a try and let you know if it works on my end.

Best,
Francisco.

**Comment by oblomov-dev** [comment] 2024-11-26 07:43
@christianguenter2 thank you for the investigation and sharing the solution! @abapsheep i think you faced the same issues, maybe therefore also interesting for you too.

**Comment by abapsheep** [comment] 2024-11-26 08:01
Hello everyone, I have exactly the same problem since an update. It is reproducible for me. Always the first ABAP2UI5 tile after a refresh does not work, but other tiles work. So if I start with another tile, the one that had previously thrown the error works again.
<img width="1134" alt="image" src="https://github.com/user-attachments/assets/28c776f5-0a78-40f2-9a84-88fea578d66e">

**Comment by rafeodev** [comment] 2024-11-28 10:54
Hi guys,

I tried to folllow the solution from @christianguenter2 but it did not work. I keep getting exactly the same error.

Let me know if you want me to do additional checks.

KR,

Mehdi

**Comment by christianguenter2** [comment] 2024-11-28 11:08
Hm, too bad. Can you try switching to tag 1.135.0-classic and check whether that makes any difference?

**Comment by rafeodev** [comment] 2024-11-28 12:00
Sure but I am quite new to this Community. What do you by "switching to tag" ?

**Comment by oblomov-dev** [comment] 2024-12-09 12:15
@rafeodev any news here?

@christianguenter2 thanks for the guideline, added your cache tricks to the documentation: 
https://abap2ui5.github.io/docs/configuration/launchpad.html#cache-management

If the installation with abapGit does not work properly there is also another workaround. Install the BSP manually with repository upload, check it out here:
https://abap2ui5.github.io/docs/configuration/launchpad.html#manual-deployment

In general the BSP works, i think we run into some troubles here because i aligned the naming of the BSP to the main abap2UI5 repository. From `zabap2ui5` to `z2ui5`. I guess this causes the ICF issues, but i hope once installed and running these problems will not occure in the future again.

**Comment by rafeodev** [comment] 2024-12-11 21:11
Hi,

Sorry, I did not get Time the Last few days. I will check this week.

**Comment by oblomov-dev** [comment] 2024-12-27 13:11
this issue got big, close this for now, create a new one if you still run into problems after latest updates.

**Closed by oblomov-dev** 2024-12-27 13:11 UTC
