### ISSUE TITLE
Internal table altered when date or time fields are empty

### ISSUE THREAD

**Issue by noso2k1** [abap2UI5/abap2UI5#1372] opened 2024-09-05 07:59 UTC
Hi there,

I stumbled upon a weird behavior when working with a table: the internal table that is bond to the TABLE object is altered when there are date or time fields empty after an event is fired. All rows in the internal table after the first row with date and time field empty are deleted.

For example an internal table like this:

```
     problematic_rows = VALUE #(
        ( id = 1 descr = 'First row' adate = sy-datum atime = sy-uzeit )
        ( id = 2 descr = 'Second row' adate = sy-datum atime = sy-uzeit )
        ( id = 3 descr = 'Third row' adate = '' atime = '' )
        ( id = 4 descr = 'Fourth row' adate = '' atime = '' )
        ( id = 5 descr = 'Fifth row' adate = sy-datum atime = sy-uzeit )  ).
```

will have rows 4 and 5 disappearing after an event is fired.

As soon as the application is opened, this is what I see:

![image](https://github.com/user-attachments/assets/b8cb8a8f-b208-44e7-860a-f0a3697bc4f2)

After I press the button (there's no code connected to the event) this is what happens to the table:

![image](https://github.com/user-attachments/assets/c8530e9e-6071-4311-9d3d-59c05e43d4a1)

As soon as date or time are set to 0, then all works fine.
I have ABAP2UI5 version 1.133.0 installed.

Here you can find an example to showcase the behavior.

[ZCL_TEST_Z2UI5_ERROR.txt](https://github.com/user-attachments/files/16885936/ZCL_TEST_Z2UI5_ERROR.txt)

Thanks and keep up the good work!

**Comment by oblomov-dev** [comment] 2024-09-05 08:41
Thank you for the detailed example, very helpful to find the error quickly. ajson throws an error because the date and time have an invalid value. made quick fix, you can check if it works now on your side. https://github.com/abap2UI5/abap2UI5/pull/1373

added your sample to the repository:
z2ui5_cl_demo_app_118

**Comment by noso2k1** [comment] 2024-09-05 09:37
I installed the main branch and now my test application behaves correctly.

Thanks for the quick solution!

**Comment by francisco-milan** [comment] 2024-09-05 16:43
Hi guys,

  I would like to propose a small change in the code:

![image](https://github.com/user-attachments/assets/b7c00fc3-e3d2-40ee-85c6-d7db8a2277a2)

To go from this:

![image](https://github.com/user-attachments/assets/5af82b5f-96d7-4775-9804-8d30bc967781)

To this:
![image](https://github.com/user-attachments/assets/515136a1-ccf1-4aca-a289-c93d8aa3861a)

**Comment by oblomov-dev** [comment] 2024-09-06 06:33
yes looks good, feel free to change the code and send a PR. Here the example was mainly to reproduce the error on column date and time.

**Comment by oblomov-dev** [comment] 2024-09-07 07:07
Hi @noso2k1,

thought again about this fix but i am not sure anymore if the latest change is the correct way to solve this. somehow with date = '' and time = '' you create invalid date and time values and abap2UI5 now passes this dirty state further. 
https://help.sap.com/doc/abapdocu_752_index_htm/7.52/en-us/abenchar_date_time_fields_validity.htm

i think it could be better to raise an exception as early as possible when invalid date/times are used. adjusted abap2UI5 therefore again: https://github.com/abap2UI5/abap2UI5/pull/1377

whenever invalid values are used now an exception is raise (instead of ignoring and creating an confusing situation as before):
<img width="1005" alt="Google Chrome 2024-09-07 09 00 14" src="https://github.com/user-attachments/assets/1dc0d335-ee07-4e03-b391-dccca8da7be6">

adjusted the demo too that you can check it on your side:
<img width="800" alt="image" src="https://github.com/user-attachments/assets/72c34a5a-194c-42e0-bb5e-af5731d6f159">

you can test the change with the actual main branch and go back to the latest working situation on your side by using:
https://github.com/abap2UI5/abap2UI5/tree/hotfix_ignore_date_time_errors

does this work for you? or is there any reason why you have to use date = '' instead of initializing it correctly?

**Comment by noso2k1** [comment] 2024-09-07 20:00
Seeing a date field to empty was a way to show the behavior. I was actually retrieving that date from a lookup to another internal table that didn’t confirm a corresponding entry, hence dates were empty.
Anyway, fine for me throwing an exception: that makes it clear what’s happening and how to solve the exception.
Thanks again for your efforts!

**Comment by oblomov-dev** [comment] 2024-09-07 22:14
ok nice, then we can keep it like this now and solved the problem with the exception right on the root. thanks for the quick feedback. i'll close this issue now.

**Closed by oblomov-dev** 2024-09-07 22:14 UTC
